import type { IndianState, Problem, User } from '@/lib/definitions';
import { DEFAULT_PROFILE_IMAGE } from '@/lib/profile';

export const indianStates: IndianState[] = [
  { code: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihar' },
  { code: 'CG', name: 'Chhattisgarh' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'DH', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' },
  { code: 'HP', name: 'Himachal Pradesh' },
  { code: 'HR', name: 'Haryana' },
  { code: 'JH', name: 'Jharkhand' },
  { code: 'JK', name: 'Jammu and Kashmir' },
  { code: 'KA', name: 'Karnataka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'MH', name: 'Maharashtra' },
  { code: 'ML', name: 'Meghalaya' },
  { code: 'MN', name: 'Manipur' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nagaland' },
  { code: 'OR', name: 'Odisha' },
  { code: 'PB', name: 'Punjab' },
  { code: 'PY', name: 'Puducherry' },
  { code: 'RJ', name: 'Rajasthan' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TG', name: 'Telangana' },
  { code: 'TN', name: 'Tamil Nadu' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UT', name: 'Uttarakhand' },
  { code: 'WB', name: 'West Bengal' },
];

export const departments = [
    "Electric Department",
    "Municipal Department",
    "Water & Sewerage",
    "Roads & Transport",
];

// Note: mockUsers and mockProblems are no longer used for live data,
// but are kept for reference or testing purposes.

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Anjali Sharma',
    mobile: '+919876543210',
    email: 'anjali.s@example.com',
    avatar_url: DEFAULT_PROFILE_IMAGE,
    civic_points: 2450,
  },
  {
    id: 'user-2',
    name: 'Rohan Verma',
    mobile: '+918765432109',
    email: 'rohan.v@example.com',
    avatar_url: DEFAULT_PROFILE_IMAGE,
    civic_points: 1500,
  },
];

export const mockProblems: Problem[] = [
  {
    id: 'prob-1',
    title: 'Massive Pothole on Main St',
    description: 'A very large and dangerous pothole has formed in the middle of Main Street, causing traffic issues and potential vehicle damage. It has been there for over two weeks.',
    department: 'Roads & Transport',
    issue_type: 'Roads & Streets',
    status: 'Resolved',
    address: 'Main Street, Bandra West, Mumbai',
    state: 'Maharashtra',
    city: 'Mumbai',
    lat: 19.0596,
    lng: 72.8295,
    media_images: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80'],
    likes: 15,
    dislikes: 2,
    reported_by: 'user-1',
    created_at: '2024-05-10T10:00:00Z',
  },
  {
    id: 'prob-2',
    title: 'Broken Streetlight Near Public Park',
    description: 'The streetlight at the entrance of the public park has been non-functional for 5 days, making the crosswalk dangerous at night for pedestrians.',
    department: 'Electric Department',
    issue_type: 'Lighting & Electricity',
    status: 'In Progress',
    address: 'Connaught Place Outer Circle, New Delhi',
    state: 'Delhi',
    city: 'New Delhi',
    lat: 28.6328,
    lng: 77.2197,
    media_images: ['https://images.unsplash.com/photo-1508873696983-2df5293cb32b?w=600&auto=format&fit=crop&q=80'],
    likes: 28,
    dislikes: 1,
    reported_by: 'user-1',
    created_at: '2024-06-15T14:30:00Z',
  },
  {
    id: 'prob-3',
    title: 'Water Main Leak Flooding Pedestrian Walkway',
    description: 'Clean drinking water is continuously gushing out of an underground supply pipe on 100 Feet Road, wasting valuable water and inundating shop fronts.',
    department: 'Water & Sewerage',
    issue_type: 'Water & Drainage',
    status: 'Registered',
    address: '100 Feet Road, Indiranagar, Bengaluru',
    state: 'Karnataka',
    city: 'Bengaluru',
    lat: 12.9716,
    lng: 77.6412,
    media_images: ['https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80'],
    likes: 42,
    dislikes: 0,
    reported_by: 'user-2',
    created_at: '2024-07-01T09:15:00Z',
  },
  {
    id: 'prob-4',
    title: 'Uncollected Garbage Dump Overflowing',
    description: 'Community waste bins have not been cleared by municipal trucks for four consecutive days. Stray animals are scattering plastic and food waste on the road.',
    department: 'Municipal Department',
    issue_type: 'Sanitation & Waste',
    status: 'Awaiting Approval',
    address: 'T. Nagar Commercial Market, Chennai',
    state: 'Tamil Nadu',
    city: 'Chennai',
    lat: 13.0418,
    lng: 80.2341,
    media_images: ['https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=600&auto=format&fit=crop&q=80'],
    likes: 19,
    dislikes: 3,
    reported_by: 'user-2',
    created_at: '2024-07-12T11:45:00Z',
  },
];
