import type { IndianState, Problem, User } from '@/lib/definitions';

export const indianStates: IndianState[] = [
  { code: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihar' },
  { code: 'CG', name: 'Chhattisgarh' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'DH', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' },
  { code: 'HP', name: 'Himachal Pradesh' },
  { code: 'HR', name: 'Haryana' },
  { code: 'JH', name: 'Jharkhand' },
  { code: 'JK', name: 'Jammu and Kashmir' },
  { code: 'KA', name: 'Karnataka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'MH', name: 'Maharashtra' },
  { code: 'ML', name: 'Meghalaya' },
  { code: 'MN', name: 'Manipur' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nagaland' },
  { code: 'OR', name: 'Odisha' },
  { code: 'PB', name: 'Punjab' },
  { code: 'PY', name: 'Puducherry' },
  { code: 'RJ', name: 'Rajasthan' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TG', name: 'Telangana' },
  { code: 'TN', name: 'Tamil Nadu' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UT', name: 'Uttarakhand' },
  { code: 'WB', name: 'West Bengal' },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Anjali Sharma',
    mobile: '9876543210',
    email: 'anjali.s@example.com',
    avatarUrl: 'https://picsum.photos/seed/avatar1/100/100',
  },
  {
    id: 'user-2',
    name: 'Rohan Verma',
    mobile: '8765432109',
    avatarUrl: 'https://picsum.photos/seed/avatar2/100/100',
  },
];

export const departments = [
    "Electric Department",
    "Municipal Department",
    "Water & Sewerage",
    "Roads & Transport",
];

export const mockProblems: Problem[] = [
  {
    id: 'prob-1',
    title: 'Massive Pothole on Main St',
    description: 'A very large and dangerous pothole has formed in the middle of Main Street, causing traffic issues and potential vehicle damage. It has been there for over two weeks.',
    department: 'Roads & Transport',
    issueType: 'Roads & Streets',
    status: 'Resolved',
    location: {
      state: 'Maharashtra',
      city: 'Mumbai',
      address: 'Main Street, Mumbai',
      coordinates: { lat: 19.076, lng: 72.8777 },
    },
    media: {
      images: ['pothole-1'],
      videos: [],
    },
    likes: 15,
    dislikes: 2,
    reportedBy: mockUsers[0],
    createdAt: '2024-05-10T10:00:00Z',
  },
  {
    id: 'prob-2',
    title: 'Garbage not collected for a week',
    description: 'The garbage bins in our locality have not been cleared for over a week. It is causing a huge mess and a health hazard.',
    department: 'Municipal Department',
    issueType: 'Waste Management',
    status: 'Pending',
    location: {
      state: 'Delhi',
      city: 'New Delhi',
      address: 'Connaught Place, New Delhi',
      coordinates: { lat: 28.6139, lng: 77.2090 },
    },
    media: {
      images: ['garbage-1'],
      videos: [],
      voicemail: 'voicemail-1.mp3',
    },
    likes: 2,
    dislikes: 0,
    reportedBy: mockUsers[1],
    createdAt: '2024-05-28T14:30:00Z',
  },
  {
    id: 'prob-3',
    title: 'Streetlight out',
    description: 'The streetlight on the corner of 5th and Elm has been out for three nights in a row, making the area very dark and unsafe.',
    department: 'Electric Department',
    issueType: 'Streetlights',
    status: 'In Progress',
    location: {
      state: 'Karnataka',
      city: 'Bengaluru',
      address: '5th and Elm, Bengaluru',
      coordinates: { lat: 12.9716, lng: 77.5946 },
    },
    media: {
      images: ['streetlight-1'],
      videos: [],
    },
    likes: 8,
    dislikes: 1,
    reportedBy: mockUsers[0],
    createdAt: '2024-05-25T21:00:00Z',
  },
  {
    id: 'prob-4',
    title: 'Major water pipe leak',
    description: 'There is a huge water leakage from a pipe on the main road. A lot of clean water is being wasted and it is flooding the street.',
    department: 'Water & Sewerage',
    issueType: 'Water & Sewage',
    status: 'Pending',
    location: {
      state: 'Delhi',
      city: 'New Delhi',
      address: 'Janpath, New Delhi',
      coordinates: { lat: 28.633, lng: 77.2167 },
    },
    media: {
      images: ['water-leak-1'],
      videos: [],
    },
    likes: 8,
    dislikes: 3,
    reportedBy: mockUsers[1],
    createdAt: '2024-05-29T08:00:00Z',
  },
    {
    id: 'prob-5',
    title: 'Broken playground equipment',
    description: 'The main swing set at the community park is broken and has sharp edges, making it dangerous for children.',
    department: 'Municipal Department',
    issueType: 'Public Spaces',
    status: 'Pending',
    location: {
      state: 'Maharashtra',
      city: 'Pune',
      address: 'Community Park, Pune',
      coordinates: { lat: 18.5204, lng: 73.8567 },
    },
    media: {
      images: ['park-1'],
      videos: [],
    },
    likes: 3,
    dislikes: 0,
    reportedBy: mockUsers[0],
    createdAt: '2024-05-27T18:00:00Z',
  },
   {
    id: 'prob-6',
    title: 'Illegal dumping in vacant lot',
    description: 'A vacant lot in our area is being used for illegal dumping of construction debris. It\'s an eyesore and environmentally harmful.',
    department: 'Municipal Department',
    issueType: 'Waste Management',
    status: 'In Progress',
    location: {
      state: 'Delhi',
      city: 'New Delhi',
      address: 'Near Nehru Place, New Delhi',
      coordinates: { lat: 28.65, lng: 77.23 },
    },
    media: {
      images: ['garbage-2'],
      videos: [],
    },
    likes: 5,
    dislikes: 5,
    reportedBy: mockUsers[0],
    createdAt: '2024-06-01T11:00:00Z',
  },
  {
    id: 'prob-7',
    title: 'Power outage every evening',
    description: 'We are experiencing daily power cuts from 7 PM to 8 PM. It is highly disruptive for everyone in the neighborhood.',
    department: 'Electric Department',
    issueType: 'Streetlights',
    status: 'Pending',
    location: {
      state: 'Maharashtra',
      city: 'Mumbai',
      address: 'Andheri West, Mumbai',
      coordinates: { lat: 19.1, lng: 72.9 },
    },
    media: {
      images: ['streetlight-2'],
      videos: [],
    },
    likes: 12,
    dislikes: 1,
    reportedBy: mockUsers[1],
    createdAt: '2024-06-02T09:00:00Z',
  },
  {
    id: 'prob-8',
    title: 'Fallen tree blocking road',
    description: 'A large tree has fallen across Oak Avenue, completely blocking traffic. Needs to be cleared urgently.',
    department: 'Roads & Transport',
    issueType: 'Roads & Streets',
    status: 'Pending',
    location: {
      state: 'Delhi',
      city: 'New Delhi',
      address: 'Oak Avenue, New Delhi',
      coordinates: { lat: 28.6139, lng: 77.2080 },
    },
    media: {
      images: ['tree-1'],
      videos: [],
    },
    likes: 0,
    dislikes: 0,
    reportedBy: mockUsers[0],
    createdAt: new Date().toISOString(),
  }
];
