

"use client";

import { createContext, useState, ReactNode, useMemo, useEffect } from 'react';
import type { User } from '@/lib/definitions';
import { onAuthStateChanged, signInWithCustomToken } from 'firebase/auth';
import { auth, db } from '@/lib/firebase-client';
import { doc, setDoc, getDoc, collection, query, where, getDocs, limit } from 'firebase/firestore';

type AuthUser =
  | { type: 'guest' }
  | { type: 'user'; data: User }
  | { type: 'admin'; data: { name: string; email: string } }
  | { type: 'department'; data: { name: string; department: string } };

type AuthContextType = {
  user: AuthUser;
  login: (type: 'user' | 'admin' | 'department', name?: string, mobile?: string) => Promise<{success: boolean, isNewUser?: boolean, error?: string}>;
  logout: () => void;
  updateUser: (updates: Partial<User>) => void;
  incrementCivicPoints: (userId: string, points: number) => void;
};

export const AuthContext = createContext<AuthContextType | undefined>(
  undefined
);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser>({ type: 'guest' });
  
   useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (firebaseUser) {
        const userRef = doc(db, "users", firebaseUser.uid);
        const userDoc = await getDoc(userRef);

        if (userDoc.exists()) {
            const idToken = await firebaseUser.getIdToken();
            const userData = { ...(userDoc.data() as User), id: firebaseUser.uid, idToken };
            setUser({ type: 'user', data: userData });
        } else {
             console.log("User document not found for authenticated user:", firebaseUser.uid);
             // This can happen during registration before the doc is created. It's not necessarily an error.
        }
      } else {
        setUser({ type: 'guest' });
      }
    });
    return () => unsubscribe();
  }, []);
  
  const login = async (type: 'user' | 'admin' | 'department', name?: string, mobile?: string): Promise<{success: boolean, isNewUser?: boolean, error?: string}> => {
    if (type === 'user') {
        if (!mobile) return { success: false, error: 'Mobile number is required.' };
        
        try {
            // For this prototype, we'll use a hardcoded custom token.
            // In a real app, this would be generated by a secure backend.
            const mockToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJtb2NrLXNpZ25pbi1mb3ItdG9rZW4ifQ.s2h2t_E8b_t_Y9p_E8b_t_Y9p_E8b_t_Y9p_E8b_";
            
            // We use a mock token to get a Firebase User object. This establishes an authenticated session.
            const userCredential = await signInWithCustomToken(auth, mockToken);
            const firebaseUser = userCredential.user;

            return new Promise((resolve) => {
                const unsubscribe = onAuthStateChanged(auth, async (authChangeUser) => {
                    if (authChangeUser && authChangeUser.uid === firebaseUser.uid) {
                        unsubscribe(); // We only need this listener for this one-time check
                        
                        const userRef = doc(db, "users", mobile); // Use mobile as the document ID
                        const userDoc = await getDoc(userRef);
                        const isNewUser = !userDoc.exists();

                        if (isNewUser) {
                             if (!name) {
                                resolve({ success: false, error: 'Name is required for registration.' });
                                return;
                            }
                            const newUser: Omit<User, 'id' | 'idToken'> = {
                                name: name,
                                mobile: mobile,
                                avatarUrl: `https://picsum.photos/seed/${name}/100/100`,
                                civicPoints: 0,
                            };
                            await setDoc(userRef, newUser);
                            setUser({ type: 'user', data: { ...newUser, id: mobile }});
                        } else {
                            setUser({ type: 'user', data: { id: mobile, ...userDoc.data() } as User});
                        }
                        
                        resolve({ success: true, isNewUser });
                    }
                });
            });

        } catch(error) {
            console.error("Firebase data handling error:", error);
            const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
            return { success: false, error: errorMessage };
        }
        
    } else if (type === 'admin') {
      setUser({ type: 'admin', data: { name: 'Admin User', email: 'admin@voice2action.com' } });
       return { success: true };
    } else if (type === 'department' && name) {
       setUser({ type: 'department', data: { name: 'Dept Head', department: name } });
       return { success: true };
    }
    return { success: false, error: 'Invalid login type.' };
  };

  const logout = () => {
    // Since we are mocking auth, we just clear the local state
    auth.signOut();
    setUser({ type: 'guest' });
  };
  
  const updateUser = async (updates: Partial<User>) => {
    if (user.type === 'user') {
        const userRef = doc(db, "users", user.data.id);
        const updatedUserData = { ...user.data, ...updates };
        try {
            await setDoc(userRef, updates, { merge: true });
            setUser({
                ...user,
                data: updatedUserData
            });
        } catch (error) {
            console.error("Error updating user document:", error);
        }
    }
  };
  
  const incrementCivicPoints = async (userId: string, points: number) => {
      if (user.type === 'user' && user.data.id === userId) {
          const userRef = doc(db, "users", userId);
          try {
            const newPoints = (user.data.civicPoints || 0) + points;
            await setDoc(userRef, { civicPoints: newPoints }, { merge: true });
            setUser(prev => ({ ...prev, data: { ...user.data, civicPoints: newPoints } } as AuthUser));
          } catch(error) {
            console.error("Error incrementing civic points:", error);
          }
      }
  };

  const value = useMemo(() => ({ user, login, logout, updateUser, incrementCivicPoints }), [user]);

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
