
"use client";

import { createContext, useState, ReactNode, useMemo, useEffect } from 'react';
import type { User } from '@/lib/definitions';
import { onAuthStateChanged, signInWithCustomToken, signOut, type User as FirebaseUser } from 'firebase/auth';
import { auth, db } from '@/lib/firebase-client';
import { doc, setDoc, getDoc, serverTimestamp } from 'firebase/firestore';

type AuthUser =
  | { type: 'guest' }
  | { type: 'loading' }
  | { type: 'user'; data: User }
  | { type: 'admin'; data: { name: string; email: string } }
  | { type: 'department'; data: { name: string; department: string } };

type AuthContextType = {
  user: AuthUser;
  login: (mobileOrUsername: string, passwordOrDepartment?: string) => Promise<{success: boolean, error?: string, userType?: 'user' | 'admin' | 'department'}>;
  register: (name: string, mobile: string) => Promise<{success: boolean, error?: string}>;
  logout: () => void;
  updateUser: (updates: Partial<User>) => void;
  incrementCivicPoints: (userId: string, points: number) => void;
};

export const AuthContext = createContext<AuthContextType | undefined>(
  undefined
);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser>({ type: 'loading' });

  // This effect hook handles the authentication state persistence
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (firebaseUser) {
        // User is signed in, see docs for a list of available properties
        // https://firebase.google.com/docs/reference/js/firebase.User
        const userDocRef = doc(db, "users", firebaseUser.uid);
        const userDoc = await getDoc(userDocRef);

        if (userDoc.exists()) {
            const userData = { id: userDoc.id, ...userDoc.data() } as User;
            setUser({ type: 'user', data: userData });
        } else {
             // This case might happen if the user's document was deleted but they are still logged in.
             // We'll log them out to be safe.
             await signOut(auth);
             setUser({ type: 'guest' });
        }
      } else {
        // User is signed out
        setUser({ type: 'guest' });
      }
    });

    return () => unsubscribe();
  }, []);


  const login = async (identifier: string, secret?: string): Promise<{success: boolean, error?: string, userType?: 'user' | 'admin' | 'department'}> => {
    // Admin login (remains a mock login)
    if (identifier === 'lowell' && secret === 'lowell') {
        const adminData = { name: 'Lowell', email: 'admin@voice2action.com' };
        setUser({ type: 'admin', data: adminData });
        return { success: true, userType: 'admin' };
    }
    
    // Department login (remains a mock login)
    if (secret && identifier === secret) { 
        setUser({ type: 'department', data: { name: secret, department: secret } });
        return { success: true, userType: 'department' };
    }
    
    // User login (now uses Firebase Auth)
    const mobile = identifier;
    try {
        // In a real app, this would be a custom token generated by a backend after verifying the mobile/OTP
        // For the prototype, we are using a mock token generation function URL which will not work in production
        // and is the source of many "Failed to fetch" errors if the service is down.
        // Let's create a simulated custom token flow
        const mockTokenResponse = await fetch(`https://us-central1-genkit-llm-demo.cloudfunctions.net/getCustomToken?uid=${mobile}`);
        if (!mockTokenResponse.ok) {
            throw new Error('Failed to get a mock authentication token.');
        }
        const { token } = await mockTokenResponse.json();

        await signInWithCustomToken(auth, token);
        // The onAuthStateChanged listener will handle setting the user state.
        
        return { success: true, userType: 'user' };
    } catch (error) {
      console.error("Login error:", error);
      const errorMessage = error instanceof Error ? error.message : "An unknown error occurred during login.";
      return { success: false, error: errorMessage };
    }
  };

  const register = async (name: string, mobile: string): Promise<{success: boolean, error?: string}> => {
    try {
        const mockTokenResponse = await fetch(`https://us-central1-genkit-llm-demo.cloudfunctions.net/getCustomToken?uid=${mobile}`);
         if (!mockTokenResponse.ok) {
            throw new Error('Failed to get a mock authentication token.');
        }
        const { token } = await mockTokenResponse.json();

        const userCredential = await signInWithCustomToken(auth, token);
        const firebaseUser = userCredential.user;

        const userDocRef = doc(db, "users", firebaseUser.uid);
        const userDoc = await getDoc(userDocRef);

        if (userDoc.exists()) {
            // This can happen if a user tries to register after already being in the system.
            // We can just log them in.
            const userData = { id: userDoc.id, ...userDoc.data() } as User;
            setUser({ type: 'user', data: userData });
            return { success: true };
        }

        const newUser: Omit<User, 'id'> = {
          name: name,
          mobile: mobile,
          avatarUrl: `https://picsum.photos/seed/${name.split(' ').join('')}/100/100`,
          civicPoints: 0,
        };
        
        await setDoc(userDocRef, newUser);
        
        const fullUser: User = { ...newUser, id: firebaseUser.uid };
        setUser({ type: 'user', data: fullUser });
      
        return { success: true };
    } catch (error) {
        console.error("Registration error:", error);
        const errorMessage = error instanceof Error ? error.message : "An unknown error occurred during registration.";
        return { success: false, error: errorMessage };
    }
  };
  
  const logout = async () => {
    // For regular users, sign out of Firebase
    if (user.type === 'user') {
      await signOut(auth);
    }
    // For all user types, reset the state to guest
    setUser({ type: 'guest' });
  };
  
  const updateUser = async (updates: Partial<User>) => {
    if (user.type === 'user') {
        const userRef = doc(db, "users", user.data.id);
        const updatedUserData = { ...user.data, ...updates };
        try {
            await setDoc(userRef, updates, { merge: true });
            setUser({
                ...user,
                data: updatedUserData
            });
        } catch (error) {
            console.error("Error updating user document:", error);
        }
    }
  };
  
  const incrementCivicPoints = async (userId: string, points: number) => {
      // This function can now correctly check against the real user ID
      if (user.type === 'user' && user.data.id === userId) {
          const userRef = doc(db, "users", userId);
          try {
            const newPoints = (user.data.civicPoints || 0) + points;
            await setDoc(userRef, { civicPoints: newPoints }, { merge: true });
            setUser(prev => {
                if (prev.type === 'user') {
                    return { type: 'user', data: { ...prev.data, civicPoints: newPoints }};
                }
                return prev;
            });
          } catch(error) {
            console.error("Error incrementing civic points:", error);
          }
      }
  };

  const value = useMemo(() => ({ user, login, register, logout, updateUser, incrementCivicPoints }), [user]);

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

    