
"use client";

import { createContext, useState, ReactNode, useMemo, useEffect } from 'react';
import type { User } from '@/lib/definitions';
import { onAuthStateChanged, signInWithCustomToken } from 'firebase/auth';
import { auth, db } from '@/lib/firebase-client'; // Using the client auth instance
import { doc, setDoc, getDoc } from 'firebase/firestore';

type AuthUser =
  | { type: 'guest' }
  | { type: 'user'; data: User }
  | { type: 'admin'; data: { name: string; email: string } }
  | { type: 'department'; data: { name: string; department: string } };

type AuthContextType = {
  user: AuthUser;
  login: (type: 'user' | 'admin' | 'department', nameOrDepartment?: string, mobile?: string) => void;
  logout: () => void;
  updateUser: (updates: Partial<User>) => void;
  incrementCivicPoints: (userId: string, points: number) => void;
};

export const AuthContext = createContext<AuthContextType | undefined>(
  undefined
);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser>({ type: 'guest' });
  
   useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (firebaseUser) {
        const token = await firebaseUser.getIdToken();
        const userRef = doc(db, "users", firebaseUser.uid);
        const userDoc = await getDoc(userRef);

        if (userDoc.exists()) {
            setUser({ type: 'user', data: { ...(userDoc.data() as User), id: firebaseUser.uid, idToken: token } });
        } else {
             // This case might happen if the user document wasn't created for some reason.
             // We can log them out or create a default profile.
             console.warn("User document not found for authenticated user:", firebaseUser.uid);
             logout();
        }
      } else {
        setUser({ type: 'guest' });
      }
    });
    return () => unsubscribe();
  }, []);


  const login = async (type: 'user' | 'admin' | 'department', nameOrDepartment?: string, mobile?: string) => {
    if (type === 'user') {
       if (nameOrDepartment && mobile) {
        // This is a new registration. We'll use a mock custom token flow.
        // In a real app, this token would be generated by a secure backend function.
        const mockUid = `user-${Date.now()}`;
        const mockToken = `mock-token-for-${mockUid}`; // This is not a real Firebase token.
        
        try {
            // In a real app, you'd call `signInWithCustomToken(auth, realTokenFromServer)`
            // For now, we'll manually create the user doc and set state.
            const newUser: User = {
                id: mockUid,
                name: nameOrDepartment,
                mobile: mobile,
                avatarUrl: `https://picsum.photos/seed/${nameOrDepartment}/100/100`,
                civicPoints: 0,
            };

            const userRef = doc(db, "users", mockUid);
            await setDoc(userRef, { name: newUser.name, mobile: newUser.mobile, avatarUrl: newUser.avatarUrl, civicPoints: newUser.civicPoints });

            setUser({ type: 'user', data: {...newUser, idToken: mockToken }});

        } catch (error) {
            console.error("Error creating user document:", error);
        }

      } else {
        // This is a login for an existing user (mocked with a custom token).
        // This part would involve a backend call to generate a custom token for a given user (e.g., via mobile OTP).
        // For simplicity, we are skipping the actual sign-in with a custom token.
        // The onAuthStateChanged listener handles setting user state for already logged-in users.
      }
    } else if (type === 'admin') {
      setUser({ type: 'admin', data: { name: 'Admin User', email: 'admin@voice2action.com' } });
    } else {
       setUser({ type: 'department', data: { name: 'Dept Head', department: nameOrDepartment || 'Roads & Transport' } });
    }
  };

  const logout = () => {
    auth.signOut();
    setUser({ type: 'guest' });
  };
  
  const updateUser = async (updates: Partial<User>) => {
    if (user.type === 'user') {
        const userRef = doc(db, "users", user.data.id);
        const updatedUserData = { ...user.data, ...updates };
        try {
            await setDoc(userRef, updates, { merge: true });
            setUser({
                ...user,
                data: updatedUserData
            });
        } catch (error) {
            console.error("Error updating user document:", error);
        }
    }
  };
  
  const incrementCivicPoints = async (userId: string, points: number) => {
      if (user.type === 'user' && user.data.id === userId) {
          const userRef = doc(db, "users", userId);
          try {
            const newPoints = (user.data.civicPoints || 0) + points;
            await setDoc(userRef, { civicPoints: newPoints }, { merge: true });
            setUser(prev => ({ ...prev, data: { ...user.data, civicPoints: newPoints } } as AuthUser));
          } catch(error) {
            console.error("Error incrementing civic points:", error);
          }
      }
  };

  const value = useMemo(() => ({ user, login, logout, updateUser, incrementCivicPoints }), [user]);

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
